// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewComment struct {
	PostID    string  `json:"postId"`
	Content   string  `json:"content"`
	Longitude float64 `json:"longitude"`
	Latitude  float64 `json:"latitude"`
}

type NewPost struct {
	Content   string  `json:"content"`
	Longitude float64 `json:"longitude"`
	Latitude  float64 `json:"latitude"`
}

type NewUser struct {
	Username string `json:"username"`
	Password string `json:"password"`
}
